spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # redis ??
  redis:
    # ??
    host: localhost
    # ??????6379
    port: 6379
    # ?????
    database: 0
    # ??
    password: 123456
    # ??????
    timeout: 10s
    lettuce:
      pool:
        # ???????????
        min-idle: 0
        # ???????????
        max-idle: 8
        # ????????????
        max-active: 8
        # #???????????????????????
        max-wait: -1ms
#????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

